using Autodesk.AutoCAD.Runtime;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Autodesk.AutoCAD.ApplicationServices;

using Autodesk.AutoCAD.DatabaseServices;

using Autodesk.AutoCAD.EditorInput;
using Autodesk.Civil.ApplicationServices;
using static Common.ExceptionHandling.ExeptionHandlingProcedures;
using Civil3DInfoTools.PipeNetworkCreating.ConfigureNetworkCreationWindow2;

[assembly: CommandClass(typeof(Civil3DInfoTools.PipeNetworkCreating.RaiseNetworkTo3dCommand))]

namespace Civil3DInfoTools.PipeNetworkCreating
{

    /// <summary>
    /// Команда для поднятия инженерных сетей в 3d
    /// ПРЕДПОЛАГАЕТ, ЧТО ИСХОДНЫЕ ДАННЫЕ ПОЛНОСТЬЮ СООТВЕТСТВУЮТ КОДИФИКАТОРУ ПО СПБ (ПО КОТОРОМУ РАБОТАЕТ БЕНТА (2018 год))
    /// допускаются изменения названий слоев и блоков
    /// обязательна точная стыковка всех линий сетей
    /// </summary>
    public class RaiseNetworkTo3dCommand
    {
        //ASSUMPTION//ASSUMPTION//ASSUMPTION//ASSUMPTION//ASSUMPTION//ASSUMPTION//ASSUMPTION//ASSUMPTION
        //ПРЕДПОЛАГАЕТСЯ, ЧТО ВСЯ СЕТЬ СОСТОИТ ТОЛЬКО ИЗ ПОЛИЛИНИЙ (МАЛОВЕРОЯТНО, ЧТО МОГУТ БЫТЬ ДУГОВЫЕ ВСТАВКИ, СЧИТАТЬ ЧТО ВСЕ СЕГМЕНТЫ ПРЯМЫЕ).
        //ОТДЕЛЬНЫЕ ПОЛИЛИНИИ СТЫКУЮТСЯ МЕЖДУ СОБОЙ (С УЧЕТОМ ДОПУСКОВ АВТОКАДА). ВОЗМОЖНА Т-ОБРАЗНАЯ СТЫКОВКА?
        //В ТОЧКАХ СТЫКОВОК МОЖЕТ БЫТЬ БЛОК КОЛОДЦА
        //(С ТОЧНЫМ СООТВЕТСТВИЕМ ТОЧКИ ВСТАВКИ БЛОКА (С УЧЕТОМ ДОПУСКОВ АВТОКАДА))
        //КОЛОДЕЦ МОЖЕТ БЫТЬ В ОТДЕЛЬНОМ ЗАДАННОМ СЛОЕ ЛИБО В СЛОЕ САМОЙ СЕТИ (ВОЗМОЖНЫЕ ТИПЫ БЛОКОВ СТРОГО ЗАДАЮТСЯ).
        //ПРИ ЭТОМ КОЛОДЦА МОЖЕТ И НЕ БЫТЬ. НА СЕТИ МОГУТ БЫТЬ И ДРУГИЕ БЛОКИ ПОМИМО КОЛОДЦЕВ, НО ОНИ ПОКА НИКАК НЕ ВЛИЯЮТ НА МОДЕЛЬ 
        //РЯДОМ С СЕТЬЮ ЕСТЬ РАЗЛИЧНЫЕ ПОДПИСИ В ТОМ ЖЕ СЛОЕ, ЧТО И СЕТЬ:
        //- НОМЕРА ПРИМЫКАНИЙ К КОЛОДЦАМ (ПРОСТО ЦИФРА, ОРИЕНТАЦИЯ - ГОРИЗОНТАЛЬНАЯ)
        //- ДИАМЕТР ТРУБЫ (НАЧИНАЕТСЯ С СОКРАЩЕННО МАТЕРИАЛ, ПРОБЕЛ, ДИАМЕТР В МИЛИМЕТРАХ, ОРИЕНТАЦИЯ ВДОЛЬ ПОЛИЛИНИИ (НЕТОЧНО!))
        //- ПОДПИСЬ ВЛАДЕЛЬЦА(НАЧИНАЕТСЯ С "вл.", ОРИЕНТАЦИЯ ВДОЛЬ ПОЛИЛИНИИ (НЕТОЧНО!))
        //- ДРУГАЯ ИНФОРМАЦИЯ (НАПРИМЕР ПОДПИСЬ "не действ.", подписи кабелей, ОРИЕНТАЦИЯ ВДОЛЬ ПОЛИЛИНИИ (НЕТОЧНО!))
        //ВИДЫ МАТЕРИАЛОВ - "ст.","бет.","чуг.","плм",
        //ПЕРЕД МАТЕРИАЛОМ МОЖЕТ БЫТЬ
        //"ф-р"  ---  футляр (сами футляры обычно находятся в отдельном слое (и подписи к ним тоже))
        //цифра  ---  количество
        //цифра/цифра  ---  какое-то количество для кабелей

        //ОТДЕЛЬНАЯ ИСТОРИЯ - ЗОНЫ КАБЕЛЕЙ. ОНИ НЕ УКЛАДЫВАЮТСЯ В ОБЩУЮ СХЕМУ
        //НУЖНА ОТДЕЛЬНАЯ УТИЛИТА ДЛЯ ПЕРЕВОДА ЗОН КАБЕЛЕЙ В ОТДЕЛЬНЫЕ ЛИНИИ КАБЕЛЕЙ

        //УЧЕСТЬ ВОЗМОЖНОСТЬ СУЩЕСТВОВАНИЯ Т-ОБРАЗНЫХ СТЫКОВОК ЛИНИЙ СЕТЕЙ!
        //ASSUMPTION//ASSUMPTION//ASSUMPTION//ASSUMPTION//ASSUMPTION//ASSUMPTION//ASSUMPTION//ASSUMPTION

        [CommandMethod("S1NF0_RaiseNetworkTo3d", CommandFlags.Modal)]
        public void RaiseNetworkTo3d()
        {
            Document doc = Application.DocumentManager.MdiActiveDocument;
            if (doc == null) return;

            Database db = doc.Database;

            Editor ed = doc.Editor;

            CivilDocument cdok = CivilDocument.GetCivilDocument(doc.Database);


            try
            {
                //в окне 
                //1. Указать слой сетки - по умолчанию по кодификатору
                //2. Указать слой крышки колодцев - по умолчанию по кодификатору
                //3. Указать слой подписи колодцев - по умолчанию по кодификатору
                //4. Указать возможные блоки колодцев - по умолчанию M5_075(самый обычный), M5_505(связи), M5_233_A(коверы). Для каждого типа блока задать тип колодца Civil.
                //5. Указать поверхность земли.
                //6. Указать путь, где хранятся файлы excel с данными о колодцах.
                //7. Заложение инженерной сети по умолчанию - для тех случаев, когда в таблицах excel нет данных о глубине заложения
                //9. Провести сеть параллельно земле если это кабель
                ConfigureNetworkCreationView configView = new ConfigureNetworkCreationView();
                ConfigureNetworkCreationViewModel viewModel = new ConfigureNetworkCreationViewModel(doc, cdok, configView);
                configView.DataContext = viewModel;
                Application.ShowModalWindow(configView);
                if (viewModel.AcceptBtnIsEnabled && viewModel.ConfigurationsAccepted)
                {

                    //TODO: Все настройки хранятся привязанными к чертежу
                    //Продолжать использовать при последующих вызовах команды если текущий документ соответствует.
                    //Удалять если соответствующий документ закрывается

                    Dictionary<int, Dictionary<string, WellData>> wellsData = viewModel.ExcelReader.WellsData;

                    //TODO?: Подсветка всех полилиний выбранного слоя сети. Дать возможность убрать из выделейия часть объектов

                    PipeNetworkGraph networkGraph = new PipeNetworkGraph(doc, viewModel);

                    //Записать квадраты сетки в RTree
                    //Записать положения блоков колодцев в RTree
                    //Записать положения подписей колодцев в RTree

                    //Записать в RTree положение всех текстовых примитивов в слое выбранной сети - это подписи сети,
                    //содержащие атрибутику, а так же привязки примыканий к колодцам
                    //При переборе текстов они дифференцируются на группы в соответствии с тем, что в них записано

                    //Записать в RTree все конечные точки полилиний сетей - для поиска Т-образных примыканий сетей

                    //Заполнение графа сетей
                    //Множество вершин, к каждой привязан список ребер, у каждого ребра ссылка на две вершины
                    //Свойства ребра: отметка начала, отметка конца, линия (последовательность 2d точек).
                    //Метод расчета отметок для каждой из точек (по интерполяции между началом и концом или на определенной глубине).
                    //Свойства узла: блок колодца если есть, поворот блока колодца

                    //Для каждого узла графа найти все примыкающие ребра (то есть совпавшие точки концов линий в пределах допуска)
                    //Для каждого сегмента линий искать точки концов линий, лежащие на этом сегменте (поиск Т-образных пересечений)
                    //При этом должны формироваться ребра графа... Все это нужно хорошо продумать


                    //Создание структур, труб и их объединение вс соответствии с графом.
                    //Создается единый Network (называется так же как слой)?
                    //Возможно нельзя присоединять трубы непосредственно друг к другу (между ними долже быть нулевой колодец)

                }

            }
            catch (System.Exception ex)
            {
                CommonException(ex, "Ошибка при создании модели сети");
            }
        }
    }
}
